### ISSUE TITLE
Is this published?

### ISSUE THREAD

**Issue by robmarkcole** [zhu-xlab/augsburg_Multimodal_Data_Set_MDaS#1]

**Comment by acamero** [comment]
The data set paper is under review. The preprint is available [here](https://essd.copernicus.org/preprints/essd-2022-155/).

_Hu, J., Liu, R., Hong, D., Camero, A., Yao, J., Schneider, M., Kurz, F., Segl, K., and Zhu, X. X.: MDAS: A New Multimodal Benchmark Dataset for Remote Sensing, Earth Syst. Sci. Data Discuss. [preprint], https://doi.org/10.5194/essd-2022-155, in review, 2022._
